# Generated by Django 6.0.6 on 2026-07-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('horarios_clases', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'PROFESORES',
            },
        ),
    ]
