# Generated by Django 6.0.6 on 2026-07-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
        ('socios', '0008_cobro_marcar_en_rojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='socio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor', to='socios.socio'),
        ),
    ]
