# Generated by Django 6.0.4 on 2026-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('profesor_id', models.IntegerField(blank=True, db_column='profesor_id', null=True)),
                ('registra_deuda', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SOCIOS',
            },
        ),
    ]
